name: Python CI/CD

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Run on the latest stable version of Ubuntu
    runs-on: ubuntu-latest

    # Define the Python versions to test against
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # Cache dependencies to speed up subsequent runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . 
          pip install pytest

      - name: Run Pytest
        run: |
          # Run pytest from the root directory to ensure paths work correctly
          pytest tests/
